# config/default.toml

[database]
host = "localhost"
port = 5432
user = "weather_user"
password = "password"
dbname = "weather_app"
sslmode = "disable"

[weather]
weather_api_url = "http://api.weatherapi.com/v1/current.json"
weather_api_key = "33750a4300aa478e8e3103625252801"

[server]
port = 9602
